import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertNoSymlink, readRegular, relativePath, sha256, verifyFile, writeJson } from '../../scripts/source.mjs';
import { builderSharedDependencies } from '../source-map-builder-kernel/prepare.mjs';
import { prepareSourceMapPathReferences } from './references.mjs';
import { PATH_SOURCES, PREFIX, bindSourceMapPaths } from './transform.mjs';
const HERE = path.dirname(fileURLToPath(import.meta.url)), REPO = path.resolve(HERE,'../../../..');
export async function pathSharedDependencies(sourceRoot) {
    const pins = await builderSharedDependencies(sourceRoot);
    const kernel = JSON.parse(await readRegular(path.join(HERE,'../source-map-builder-kernel/sources.lock.json')));
    pins.push(...[...kernel.prepared,kernel.hostOutput].map(pin => ({component:'sourceMapBuilderKernelReceipt',path:pin.path,bytes:pin.bytes,sha256:pin.sha256,gitBlob:pin.gitBlob})));
    const config=JSON.parse(await readRegular(path.join(HERE,'../config/sources.lock.json')));
    for(const pin of config.sources){let code=verifyFile(await readRegular(path.join(sourceRoot,pin.path)),pin).toString().replace('import com.intellij.openapi.util.Key','import org.jetbrains.kotlin.portable.config.IdentityKey as Key');if(pin.path.endsWith('/CompilerConfiguration.kt')){code=code.replace('import java.util.*','import org.jetbrains.kotlin.portable.config.unmodifiableConfigurationValue');const start=code.indexOf('    companion object {'),end=code.indexOf('\n    @Internals',start);assert(start>=0&&end>start);assert.equal(sha256(Buffer.from(code.slice(start,end))),config.unmodifiableBlockSha256);code=code.slice(0,start)+'    companion object {\n        private fun <T> T.unmodifiable(): T = unmodifiableConfigurationValue()\n    }\n'+code.slice(end);}else code=code.replace('import org.jetbrains.kotlin.portable.config.IdentityKey as Key','import org.jetbrains.kotlin.portable.config.IdentityKey as Key\nimport kotlin.jvm.JvmStatic');const bytes=Buffer.from(code);pins.push({component:'configurationReceipt',path:'compiler-port-config/'+path.basename(pin.path),bytes:bytes.length,sha256:sha256(bytes)});}
    const host=await readRegular(path.join(HERE,'../config/ConfigurationHost.kt'));pins.push({component:'configurationReceipt',path:'compiler-port-config/ConfigurationHost.kt',bytes:host.length,sha256:sha256(host)});
    assert.equal(new Set(pins.map(pin => pin.path)).size,pins.length); return pins;
}
export async function readSourceMapPathLock(sourceRoot) {
    const bytes = await readRegular(path.join(HERE,'sources.lock.json')),lock=JSON.parse(bytes);
    const closureBytes=await readRegular(path.join(HERE,'../closure.lock.json')),closure=JSON.parse(closureBytes);
    assert.equal(lock.schemaVersion,1);assert.equal(lock.kind,'genuine-source-map-path-consumer');
    assert.deepEqual(lock.source,closure.source);assert.equal(lock.primaryClosureSha256,sha256(closureBytes));
    assert.deepEqual(lock.sources,PATH_SOURCES.map(name=>closure.files.find(pin=>pin.path===name)));
    for(const pin of [...lock.tools,...lock.observers,...lock.dependencies,lock.host]) verifyFile(await readRegular(path.join(HERE,pin.path)),pin);
    const references=await prepareSourceMapPathReferences();assert.deepEqual(references.files.map(({filename,...pin})=>pin),lock.references);
    for(const pin of lock.referenceDependencies) assert.deepEqual(pin,closure.files.find(item=>item.path===pin.path));
    assert.deepEqual(lock.sharedDependencies,await pathSharedDependencies(sourceRoot));
    assert.equal(lock.hostContract,'Request-owned POSIX lexical cwd, presence, diagnostics and source-map-specific output directory; general native File configuration remains separate.');
    for(const field of ['wholeCallerExecuted','generalNativeFileConfiguration','fullCompilerBuilt','languageReadiness']) assert.equal(lock[field],false);
    return {bytes,lock};
}
async function inputs(sourceRoot){const i=await readSourceMapPathLock(sourceRoot),transformed=[],snapshot=[];for(const pin of i.lock.sources){const original=verifyFile(await readRegular(path.join(sourceRoot,pin.path)),pin);transformed.push(bindSourceMapPaths(pin.path,original));snapshot.push({path:pin.path,filename:path.join(sourceRoot,pin.path),source:original.toString("base64")});}for(const [index,value]of transformed.entries())verifyFile(value.bytes,i.lock.prepared[index]);const snapshotBytes=Buffer.from(JSON.stringify(snapshot,null,2)+"\n");return {...i,transformed,snapshot,snapshotBytes};}
export function sourceMapPathsReceiptFor(i){return {schemaVersion:1,kind:'genuine-source-map-path-consumer-preparation',source:i.lock.source,sourceLockSha256:sha256(i.bytes),primaryClosureSha256:i.lock.primaryClosureSha256,preparationToolSha256:i.lock.tools.find(pin=>pin.path==='prepare.mjs').sha256,originalInputs:i.lock.sources,callerSnapshot:{path:"caller-snapshot.json",bytes:i.snapshotBytes.length,sha256:sha256(i.snapshotBytes)},tools:i.lock.tools,sharedDependencies:i.lock.sharedDependencies,referenceDependencies:i.lock.referenceDependencies,references:i.lock.references,files:[...i.lock.prepared.map((pin,index)=>({...pin,changes:i.transformed[index].changes})),i.lock.hostOutput],hostContract:i.lock.hostContract,originalSourceUnmodified:true,originalMethodsRemoved:false,javaFacadeIntroduced:false,differentialValidated:false,wholeCallerExecuted:false,generalNativeFileConfiguration:false,fullCompilerBuilt:false,languageReadiness:false};}
function roots(sourceRoot,outputRoot){assert(outputRoot.startsWith(path.join(REPO,'out')+path.sep));assert(sourceRoot!==outputRoot&&!sourceRoot.startsWith(outputRoot+path.sep)&&!outputRoot.startsWith(sourceRoot+path.sep));}
export async function prepareSourceMapPaths({sourceRoot,outputRoot}){sourceRoot=path.resolve(sourceRoot);outputRoot=path.resolve(outputRoot);roots(sourceRoot,outputRoot);await assertNoSymlink(sourceRoot);await assertNoSymlink(outputRoot);const i=await inputs(sourceRoot),receipt=sourceMapPathsReceiptFor(i),commonSources=[];const buffers=[...i.transformed.map(value=>value.bytes),verifyFile(await readRegular(path.join(HERE,i.lock.host.path)),i.lock.host)];for(const [index,pin]of receipt.files.entries()){const filename=path.join(outputRoot,relativePath(pin.path));await assertNoSymlink(filename);await mkdir(path.dirname(filename),{recursive:true,mode:0o700});await writeFile(filename,buffers[index],{flag:'wx',mode:0o600});commonSources.push(filename);}await writeFile(path.join(outputRoot,"caller-snapshot.json"),i.snapshotBytes,{flag:"wx",mode:0o600});const receiptPath=path.join(outputRoot,'source-map-path-consumer-inputs.json');await writeJson(receiptPath,receipt);return {commonSources,replacedOriginalPaths:PATH_SOURCES,sharedDependencies:receipt.sharedDependencies,receipt,receiptPath};}
export async function verifySourceMapPaths({sourceRoot,outputRoot,receiptPath}){sourceRoot=path.resolve(sourceRoot);outputRoot=path.resolve(outputRoot);roots(sourceRoot,outputRoot);await assertNoSymlink(sourceRoot);await assertNoSymlink(outputRoot);const i=await inputs(sourceRoot),receipt=sourceMapPathsReceiptFor(i);for(const pin of receipt.files)verifyFile(await readRegular(path.join(outputRoot,relativePath(pin.path))),pin);const snapshot=await readRegular(path.join(outputRoot,receipt.callerSnapshot.path));assert.equal(snapshot.length,receipt.callerSnapshot.bytes);assert.equal(sha256(snapshot),receipt.callerSnapshot.sha256);assert.equal(path.resolve(receiptPath),path.join(outputRoot,'source-map-path-consumer-inputs.json'));assert.deepEqual(JSON.parse(await readRegular(receiptPath)),receipt);return receipt;}
