import {writeFile} from 'node:fs/promises';
import path from 'node:path';import {fileURLToPath} from 'node:url';
import {gitBlob,readRegular,sha256,verifyFile} from '../../scripts/source.mjs';
import {pathSharedDependencies} from './prepare.mjs';import {PATH_SOURCES,PREFIX,bindSourceMapPaths} from './transform.mjs';
const HERE=path.dirname(fileURLToPath(import.meta.url)),REPO=path.resolve(HERE,'../../../..'),sourceRoot=path.join(REPO,'out/kotlin-compiler-port/sources');
async function pin(name){const bytes=await readRegular(path.join(HERE,name));return {path:name,bytes:bytes.length,sha256:sha256(bytes),gitBlob:gitBlob(bytes)};}
const closureBytes=await readRegular(path.join(HERE,'../closure.lock.json')),closure=JSON.parse(closureBytes);
const sources=PATH_SOURCES.map(name=>closure.files.find(pin=>pin.path===name)),prepared=[];
for(const original of sources){const bytes=bindSourceMapPaths(original.path,verifyFile(await readRegular(path.join(sourceRoot,original.path)),original)).bytes;prepared.push({path:PREFIX+original.path,bytes:bytes.length,sha256:sha256(bytes),gitBlob:gitBlob(bytes),originalPath:original.path});}
const host=await pin('SourceMapPathHost.kt');
const lock={schemaVersion:1,kind:'genuine-source-map-path-consumer',source:closure.source,primaryClosureSha256:sha256(closureBytes),sources,prepared,host,hostOutput:{...host,path:PREFIX+'org/jetbrains/kotlin/js/portable/sourcemap/SourceMapPathHost.kt'},sharedDependencies:await pathSharedDependencies(sourceRoot),references:JSON.parse(await readRegular(path.join(REPO,'out/kotlin-source-map-path-consumer/references/inventory.json'))).map(({filename,...pin})=>pin),referenceDependencies:closure.files.filter(pin=>['core/util.runtime/src/org/jetbrains/kotlin/utils/addToStdlib.kt','compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/LoweringContext.kt','js/js.config/gen/org/jetbrains/kotlin/js/config/JSConfigurationKeys.kt','js/js.config/src/org/jetbrains/kotlin/js/config/SourceMapNamesPolicy.kt','js/js.config/src/org/jetbrains/kotlin/js/config/SourceMapSourceEmbedding.kt','wasm/wasm.ir/src/org/jetbrains/kotlin/wasm/ir/source/location/SourceLocation.kt','wasm/wasm.ir/src/org/jetbrains/kotlin/wasm/ir/source/location/SourceLocationMapping.kt','wasm/wasm.ir/src/org/jetbrains/kotlin/wasm/ir/debug/DebugInfo.kt','wasm/wasm.ir/src/org/jetbrains/kotlin/wasm/ir/debug/DebugInformationGenerator.kt'].includes(pin.path)),tools:await Promise.all(['transform.mjs','prepare.mjs','update-recipe.mjs','check.mjs','final.mjs','project-callers.mjs','references.mjs','integrity.test.mjs','verify.mjs','runtime-composition.mjs'].map(pin)),observers:await Promise.all(['Probe.kt','OriginalSupport.kt','CommonSupport.kt','JvmEntry.kt','WasmEntry.kt','HostContractProbe.kt'].map(pin)),dependencies:await Promise.all(['../closure.lock.json','../build-flags.json','../source-map-builder-kernel/sources.lock.json','../source-map-builder-kernel/prepare.mjs','../js-ast/sources.lock.json','../js-ast/adapt.mjs','../source-map-json/sources.lock.json','../source-map-text-io/sources.lock.json','../text/sources.lock.json','../config/sources.lock.json','../config/prepare.mjs','../config/ConfigurationHost.kt','../source-map-runtime/final.mjs','../source-map-runtime/sources.lock.json'].map(pin)),hostContract:'Request-owned POSIX lexical cwd, presence, diagnostics and source-map-specific output directory; general native File configuration remains separate.',wholeCallerExecuted:false,generalNativeFileConfiguration:false,fullCompilerBuilt:false,languageReadiness:false};await writeFile(path.join(HERE,'sources.lock.json'),JSON.stringify(lock,null,2)+'\n');console.log(JSON.stringify({sources:sources.length,prepared:prepared.length+1,shared:lock.sharedDependencies.length}));
