#!/usr/bin/env python3
"""Generate a static symbol table for Lean's IR interpreter in statically linked Emscripten builds.

Usage: gen-symtab.py <c-root> <out.c>
Collects every LEAN_EXPORT function/variable declared in the Lean-generated C files.  When a
`X___boxed` variant exists, `X` itself is omitted because the interpreter always prefers the
boxed variant (see lookup_symbol in src/library/ir_interpreter.cpp).
"""
import os, re, sys
root, out = sys.argv[1], sys.argv[2]
fn_re = re.compile(r'^LEAN_EXPORT (.+?[\s\*])(\w+)\((.*)\)\s*[;{]\s*$')
var_re = re.compile(r'^LEAN_EXPORT (.+?[\s\*])(\w+)\s*;\s*$')
funcs, vars_ = {}, {}
files = []
for d, _, fs in os.walk(root):
    for f in fs:
        if f.endswith('.c'):
            files.append(os.path.join(d, f))
files.sort()
for path in files:
    with open(path, encoding='utf-8') as fh:
        for line in fh:
            if not line.startswith('LEAN_EXPORT '):
                continue
            m = fn_re.match(line)
            if m:
                ret, name, params = m.group(1).strip(), m.group(2), m.group(3)
                # drop parameter names: Lean emits "type x_1" in definitions
                ps = []
                for p in params.split(',') if params.strip() else []:
                    p = p.strip()
                    pm = re.match(r'^(.*?[\s\*])(\w+)$', p)
                    ps.append(pm.group(1).strip() if pm and pm.group(2) not in ('void',) and not re.match(r'^(lean_object|uint8_t|uint16_t|uint32_t|uint64_t|size_t|double|float|lean_obj_arg|b_lean_obj_arg)$', pm.group(2)) else p)
                funcs.setdefault(name, (ret, ps))
                continue
            m = var_re.match(line)
            if m:
                vars_.setdefault(m.group(2), m.group(1).strip())
names = {}
for n, sig in funcs.items():
    if n + '___boxed' in funcs:
        continue
    names[n] = ('f', sig)
for n, t in vars_.items():
    if n in funcs:
        continue
    names[n] = ('v', t)
order = sorted(names, key=lambda s: s.encode())
with open(out, 'w', encoding='utf-8') as o:
    o.write('// Generated by wasm-llvm lean-browser gen-symtab.py. Do not edit.\n')
    o.write('#include <lean/lean.h>\n#include <string.h>\n#include <stdlib.h>\n')
    for n in order:
        kind, sig = names[n]
        if kind == 'f':
            ret, ps = sig
            o.write(f'extern {ret} {n}({", ".join(ps) if ps else "void"});\n')
        else:
            o.write(f'extern {sig} {n};\n')
    o.write('typedef struct { const char * name; void * addr; } lean_wasm_sym;\n')
    o.write('static const lean_wasm_sym lean_wasm_syms[] = {\n')
    for n in order:
        o.write(f'  {{"{n}", (void*)&{n}}},\n')
    o.write('};\n')
    o.write('static int lean_wasm_sym_cmp(const void * k, const void * e) {\n'
            '  return strcmp((const char *)k, ((const lean_wasm_sym *)e)->name);\n}\n')
    o.write('LEAN_EXPORT void * lean_emscripten_lookup_symbol(char const * sym) {\n'
            '  const lean_wasm_sym * r = (const lean_wasm_sym *)bsearch(sym, lean_wasm_syms,\n'
            '    sizeof(lean_wasm_syms) / sizeof(lean_wasm_syms[0]), sizeof(lean_wasm_syms[0]), lean_wasm_sym_cmp);\n'
            '  return r ? r->addr : NULL;\n}\n')
print(f'{len(files)} files, {len(funcs)} functions, {len(vars_)} variables, {len(order)} table entries')
