import assert from 'node:assert/strict';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {readRegular,sha256,verifyFile,writeJson,assertNoSymlink} from '../../scripts/source.mjs';
import {normalizeRecordedImports} from '../serializer-output-bindings/transform.mjs';
import {inspectNativeJsOutputInputs,bindNativeJsOutputBackend,inspectNativeJsOutputSelection,nativeJsOutputReceiptFor,roots,TARGET,FRAGMENT,ENUM_IMPORT,identity} from './prepare.mjs';
const HERE=path.dirname(fileURLToPath(import.meta.url)),REPO=path.resolve(HERE,'../../../..'),ASSERT_IMPORT='org.jetbrains.kotlin.portable.assertions.compilerAssert as assert';
export async function verifyNativeJsOutputFinalSources({sourceRoot,outputRoot,receiptPath,preparedBackendProfile,preparedProfile,retainedSources,allowedAddedImports=[],verifiedModuleBoundary,finalOutputRoot=path.join(outputRoot,'final')}){
 outputRoot=path.resolve(outputRoot);roots(path.resolve(sourceRoot),outputRoot);await assertNoSymlink(outputRoot);assert.equal(path.resolve(receiptPath),path.join(outputRoot,'native-js-output-inputs.json'));assert.equal(preparedProfile.receiptPath,receiptPath);const bytes=await readRegular(receiptPath),receipt=JSON.parse(bytes);assert.equal(sha256(bytes),preparedProfile.receiptSha256,'Initial preparation receipt changed after validation');assert.deepEqual(receipt,preparedProfile.receipt);assert.deepEqual(preparedProfile.commonSources,[]);assert.deepEqual(preparedProfile.sourceSetExclusions,[TARGET]);assert.deepEqual(preparedProfile.originalReferenceSources,[path.join(outputRoot,'original/'+TARGET)]);const i=await inspectNativeJsOutputInputs(sourceRoot),binding=await bindNativeJsOutputBackend(i,preparedBackendProfile);assert.deepEqual(receipt,nativeJsOutputReceiptFor(i,binding,{...receipt.selection,boundaries:receipt.retainedBoundaries,splitBoundaries:receipt.retainedSplits}));
 verifyFile(await readRegular(path.join(outputRoot,receipt.originalReference.path)),i.lock.target);assert.equal(receipt.originalReference.path,'original/'+TARGET);const selected=await inspectNativeJsOutputSelection(i,retainedSources,{excludeTarget:true});assert(Array.isArray(allowedAddedImports)&&new Set(allowedAddedImports).size===allowedAddedImports.length);for(const name of allowedAddedImports)assert(/^[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*(?:\.\*)?(?: as [A-Za-z_]\w*)?$/.test(name));const propertyImports=allowedAddedImports.filter(name=>!['kotlin.jvm.*',ASSERT_IMPORT].includes(name));
 assert.equal(receipt.retainedBoundaries.length,i.lock.requiredBoundaries.length);assert.equal(receipt.retainedSplits.length,i.lock.existingSplits.length);const bindings=[];const ordered=i.lock.requiredBoundaries.map((pin,index)=>({pin,index})).sort((a,b)=>(a.pin.path===FRAGMENT?1:0)-(b.pin.path===FRAGMENT?1:0));
 for(const {pin:original,index}of ordered){const prior=receipt.retainedBoundaries[index],actual=selected.boundaries[index];assert.equal(prior.originalPath,original.path);assert.equal(actual.originalPath,original.path);assert.equal(actual.path,prior.path);const canonical=verifyFile(Buffer.from(prior.source,'base64'),original);assert.deepEqual(identity(canonical),{bytes:prior.bytes,sha256:prior.sha256});const normalized=normalizeRecordedImports(Buffer.from(actual.source,'base64'),propertyImports);let adaptation;
  if(original.path===FRAGMENT&&verifiedModuleBoundary){
   const root=path.resolve(verifiedModuleBoundary.outputRoot);assert.equal(root,verifiedModuleBoundary.outputRoot);assert(root.startsWith(path.join(REPO,'out')+path.sep));await assertNoSymlink(root);const lock=JSON.parse(await readRegular(path.join(HERE,'../module-relative-paths/sources.lock.json'))),inventory=JSON.parse(verifyFile(await readRegular(path.join(HERE,'../module-relative-paths/inventory.json')),lock.inventory));assert.equal(inventory.path,FRAGMENT);assert.deepEqual(lock.source,i.lock.source);assert.equal(actual.filename,path.join(root,inventory.path),'Noncanonical actual module fragment');verifyFile(normalized,inventory.output);
   const moduleReceipt=JSON.parse(await readRegular(path.join(root,'module-relative-path-inputs.json'),32*1024*1024));assert.equal(moduleReceipt.kind,'genuine-module-relative-path-preparation');assert.equal(moduleReceipt.sourceLockSha256,sha256(await readRegular(path.join(HERE,'../module-relative-paths/sources.lock.json'))));assert.deepEqual(moduleReceipt.files,[{path:FRAGMENT,...inventory.output},{...lock.helper,path:lock.helper.outputPath}]);for(const field of ['newSourceExclusions','javaFileFacadeIntroduced','windowsHostParity','fullModuleGraphWasmExecuted','fullCompilerBuilt','languageReadiness'])assert.equal(moduleReceipt[field],false);
   const proof=verifiedModuleBoundary.final;assert.equal(proof.canonicalReconstruction,true);assert.equal(proof.actualFinalSources,selected.inspectedFiles);assert.equal(proof.reconstructedPath,FRAGMENT);assert.equal(proof.removedHelperPath,lock.helper.outputPath);assert.equal(proof.fullGraphRebuilt,false);assert.equal(proof.fullModuleGraphWasmExecuted,false);assert.equal(proof.final.phase,'after');assert.deepEqual(proof.final.inputs,selected.sources.map(({source,...pin})=>pin).sort((a,b)=>a.path.localeCompare(b.path)),'Module proof does not bind current actual graph');assert.deepEqual(proof.final.helperConsumers,[FRAGMENT,lock.helper.outputPath].sort());assert.equal(proof.commentFinal.canonicalReconstruction,true);assert.equal(proof.commentFinal.predecessorSelection.phase,'after');
   const helper=selected.sources.find(pin=>pin.path===lock.helper.outputPath);assert(helper);assert.equal(helper.filename,path.join(root,lock.helper.outputPath));verifyFile(normalizeRecordedImports(Buffer.from(helper.source,'base64'),propertyImports),lock.helper);adaptation={component:'moduleRequirePathsReceipt',filename:actual.filename,outputPin:inventory.output,sourceLockSha256:moduleReceipt.sourceLockSha256,preparationReceiptSha256:sha256(await readRegular(path.join(root,'module-relative-path-inputs.json'),32*1024*1024)),fullActualProofBound:true};
  }else{assert.equal(actual.filename,prior.filename,'Retained genuine boundary owner changed');let expected=canonical;if(original.path===ENUM_IMPORT.path){assert.equal(canonical.toString().split('import '+ENUM_IMPORT.before+'\n').length,2);expected=Buffer.from(canonical.toString().replace('import '+ENUM_IMPORT.before+'\n','import '+ENUM_IMPORT.after+'\n'));adaptation={staticImportBinding:ENUM_IMPORT};}assert.deepEqual(normalized,expected,'Retained genuine boundary bytes changed: '+actual.path);}
  bindings.push({originalPath:original.path,path:actual.path,filename:actual.filename,bytes:actual.bytes,sha256:actual.sha256,canonicalSha256:prior.sha256,adaptation:adaptation??null});
 }
 finalOutputRoot=path.resolve(finalOutputRoot);assert(finalOutputRoot.startsWith(outputRoot+path.sep));await assertNoSymlink(finalOutputRoot);const final={schemaVersion:1,kind:'wasm-unreachable-native-js-output-final-selection',source:i.lock.source,preparationReceiptSha256:sha256(bytes),inspectedFiles:selected.inspectedFiles,inspectedBytes:selected.inspectedBytes,inventorySha256:selected.inventorySha256,incoming:selected.incoming,existingProfileClosure:selected.existingProfileClosure,existingSplitBindings:selected.splitBoundaries.map(({source,...pin})=>pin),excluded:[TARGET],retainedBoundaryBindings:bindings,allowedAddedImports,limitation:receipt.limitation,existingProfileChanged:false,shippingFilesystemImplemented:false,compilerBuilt:false,languageReadiness:false};const finalPath=path.join(finalOutputRoot,'native-js-output-final.json');await writeJson(finalPath,final);return {receipt:final,receiptPath:finalPath};
}
