import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';import {fileURLToPath} from 'node:url';
import {assertNoSymlink,readRegular,relativePath,sha256,verifyFile,writeJson} from '../../scripts/source.mjs';
import {CANDIDATE_FILES,SPLITS,generateBackendSplit} from '../backend-profile/generate.mjs';
import {selectedDeclarations,chooseExclusions} from '../backend-profile/references.mjs';
import {nativeOutputReferences,combinedReferenceText,lexicalReferenceView} from './references.mjs';
export const TARGET='compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/transformers/irToJs/CompilationOutputs.kt';
const HERE=path.dirname(fileURLToPath(import.meta.url)),REPO=path.resolve(HERE,'../../../..');
export const identity=bytes=>({bytes:bytes.length,sha256:sha256(bytes)});
export const FRAGMENT='compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/transformers/irToJs/JsIrProgramFragment.kt';
export const ENUM_IMPORT={path:'compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/lower/EnumClassLowering.kt',before:'org.jetbrains.kotlin.descriptors.DescriptorVisibilities.PRIVATE',after:'org.jetbrains.kotlin.descriptors.DescriptorVisibilities.Companion.PRIVATE'};
export async function readNativeJsOutputLock(){
 const bytes=await readRegular(path.join(HERE,'sources.lock.json')),lock=JSON.parse(bytes),closureBytes=await readRegular(path.join(HERE,'../closure.lock.json')),closure=JSON.parse(closureBytes);
 assert.equal(lock.schemaVersion,1);assert.equal(lock.kind,'wasm-unreachable-native-js-output-profile');assert.deepEqual(lock.source,closure.source);assert.equal(lock.primaryClosureSha256,sha256(closureBytes));assert.deepEqual(lock.target,closure.files.find(pin=>pin.path===TARGET));
 for(const pin of [...lock.tools,...lock.dependencies])verifyFile(await readRegular(path.join(HERE,pin.path)),pin);assert.deepEqual(lock.allowedStaticImportBinding,ENUM_IMPORT);
 const backend=JSON.parse(await readRegular(path.join(HERE,'../backend-profile/sources.lock.json')));assert.equal(lock.backendProfileSourceLockSha256,sha256(await readRegular(path.join(HERE,'../backend-profile/sources.lock.json'))));assert.deepEqual(lock.existingExclusions,CANDIDATE_FILES);assert.deepEqual(lock.existingSplits,SPLITS);assert.deepEqual(lock.requiredBoundaries,[...backend.retainedBoundaries,...lock.requiredTypes]);
 for(const pin of lock.requiredTypes)assert.deepEqual(pin,closure.files.find(item=>item.path===pin.path));
 for(const field of ['shippingFilesystemImplemented','compilerBuilt','languageReadiness'])assert.equal(lock[field],false);
 return {bytes,lock,closure,backend};
}
export async function inspectNativeJsOutputInputs(sourceRoot){
 sourceRoot=path.resolve(sourceRoot);await assertNoSymlink(sourceRoot);const i=await readNativeJsOutputLock(),originals=new Map(),primary=[];
 const originalPins=i.closure.files.filter(pin=>pin.compile&&pin.path.endsWith('.kt'));for(let offset=0;offset<originalPins.length;offset+=24){const batch=await Promise.allSettled(originalPins.slice(offset,offset+24).map(async pin=>({pin,bytes:verifyFile(await readRegular(path.join(sourceRoot,pin.path)),pin)})));for(const item of batch){if(item.status!=='fulfilled')throw item.reason;primary.push(item.value.pin);originals.set(item.value.pin.path,item.value.bytes.toString());}}
 assert.equal(primary.length,i.backend.primaryKotlinSources);const original=verifyFile(await readRegular(path.join(sourceRoot,TARGET)),i.lock.target);assert.deepEqual(selectedDeclarations(original.toString()),i.lock.declarations);
 assert.deepEqual(original.toString().split('\n').map((text,index)=>({line:index+1,text})).filter(item=>/^\s*(?:(?:private|internal|protected|abstract|override) )*(?:class|fun|val|var)\b/.test(item.text)),i.lock.memberAndLocalHeaders);
 const canonical=new Map([...originals].filter(([name])=>name!==TARGET&&!CANDIDATE_FILES.includes(name)&&!SPLITS.some(rule=>rule.path===name)));
 for(const [index,rule]of SPLITS.entries()){const bytes=generateBackendSplit(Buffer.from(originals.get(rule.path)),rule).bytes;assert.deepEqual(identity(bytes),i.backend.splits[index].generated);canonical.set(rule.path,bytes.toString());}
 const originalIncoming=[];for(const [caller,text]of originals)if(caller!==TARGET){const view=lexicalReferenceView(text);for(const declaration of i.lock.declarations){const reasons=nativeOutputReferences(text,declaration,view);if(reasons.length)originalIncoming.push({caller,declaration:declaration.name,reasons});}}
 const primaryIncoming=[];for(const [caller,text]of canonical){const view=lexicalReferenceView(text);for(const declaration of i.lock.declarations){const reasons=nativeOutputReferences(text,declaration,view);if(reasons.length)primaryIncoming.push({caller,declaration:declaration.name,reasons});}}assert.deepEqual(primaryIncoming,[],'Pinned primary has a retained native JS output consumer');
 const candidates=new Map(i.backend.exclusionCandidates.map(pin=>[pin.path,{text:originals.get(pin.path),declarations:pin.declarations}]));const splitTemplates=new Map(i.backend.splits.map(pin=>[pin.path,{text:canonical.get(pin.path),removedDeclarations:pin.removedDeclarations}]));const primaryExistingProfile=closedExistingProfile(candidates,splitTemplates,new Map([...canonical].filter(([name])=>!splitTemplates.has(name)).map(([name,text])=>[name,{text}])));
 return {...i,original,primaryInventory:primary,primaryIncoming,originalIncoming,candidates,splitTemplates,primaryExistingProfile};
}
function closedExistingProfile(candidates,splits,retained){const view=values=>new Map([...values].map(([name,source])=>[name,{...source,text:combinedReferenceText(source.text)}]));const {excluded,promoted,unclosed}=chooseExclusions({candidates:view(candidates),splits:view(splits),retained:view(retained)});assert.deepEqual(excluded,[...CANDIDATE_FILES].sort(),'Existing excluded symbol now has a retained consumer');assert.deepEqual(promoted,[]);assert.deepEqual(unclosed,[],'Existing removed split symbol now has a retained consumer');return {excluded,promoted,unclosed};}
export async function bindNativeJsOutputBackend(i,component){
 const receiptPath=path.resolve(component.receiptPath),root=path.dirname(receiptPath);assert.equal(component.receiptPath,receiptPath);assert.equal(receiptPath,path.join(root,'receipt.json'));assert(root.startsWith(path.join(REPO,'out')+path.sep)&&root.endsWith('/compiler-port-backend-profile'));await assertNoSymlink(root);
 const bytes=await readRegular(receiptPath),receipt=JSON.parse(bytes);assert.deepEqual(component.receipt,receipt);assert.equal(receipt.kind,'official-wasm-whole-rebuild-source-profile-preparation');assert.deepEqual(receipt.source,i.lock.source);assert.equal(receipt.sourceLockSha256,i.lock.backendProfileSourceLockSha256);assert.deepEqual(receipt.sourceSetExclusions,CANDIDATE_FILES);assert.deepEqual(component.sourceSetExclusions,CANDIDATE_FILES);assert.deepEqual(component.replacedOriginalPaths,SPLITS.map(rule=>rule.path));assert.deepEqual(receipt.replacedOriginalPaths,SPLITS.map(rule=>rule.path));assert.deepEqual(component.commonSources,receipt.files.map(pin=>path.join(root,pin.path)));assert.deepEqual(receipt.commonSources,component.commonSources);
 assert.equal(receipt.preparationToolSha256,i.lock.dependencies.find(pin=>pin.path==='../backend-profile/prepare.mjs').sha256);assert.deepEqual(receipt.retainedBoundaries,i.backend.retainedBoundaries);assert.equal(receipt.requiresCompositionLast,true);assert.equal(receipt.lowerings,'All common/Wasm and nine Wasm-used JS lowering files and original phase order retained');assert.equal(receipt.originalSourceUnmodified,true);assert.equal(receipt.languageReadiness,false);assert.equal(receipt.browserCompilerBuilt,false);assert.equal(receipt.browserCompiledNewSource,false);assert.equal(receipt.compilerSourceBuild,'not-run for this source profile');
 assert.equal(receipt.sourceSelection.excludedOriginalFiles,CANDIDATE_FILES.length);assert.equal(receipt.sourceSelection.splitOriginalFiles,SPLITS.length);assert.deepEqual(receipt.sourceSelection.primaryIncomingReferences,[]);assert.deepEqual(receipt.sourceSelection.composedIncomingReferences,[]);
 assert.equal(receipt.files.length,SPLITS.length);for(const [index,pin]of receipt.files.entries()){assert.equal(pin.path,SPLITS[index].path);assert.deepEqual({bytes:pin.bytes,sha256:pin.sha256},i.backend.splits[index].generated);assert.equal(pin.originalSha256,i.backend.splits[index].sha256);}
 return {receiptPath,receiptSha256:sha256(bytes),commonSources:component.commonSources,sourceLockSha256:receipt.sourceLockSha256,sourceSetExclusions:CANDIDATE_FILES,replacedOriginalPaths:SPLITS.map(rule=>rule.path)};
}
export async function inspectNativeJsOutputSelection(i,retainedSources,{excludeTarget=false,backendBinding}={}){
 assert(Array.isArray(retainedSources)&&retainedSources.length>0&&retainedSources.length<=20000);const sources=[],incoming=[],seen=new Set(),filenames=new Set();let bytesTotal=0;
 const active=retainedSources.filter(item=>item.compile!==false);for(let offset=0;offset<active.length;offset+=24){const batch=await Promise.allSettled(active.slice(offset,offset+24).map(async item=>({item,bytes:await readRegular(path.resolve(item.filename))})));for(const result of batch){if(result.status!=='fulfilled')throw result.reason;const {item,bytes}=result.value;relativePath(item.path);assert(item.path.endsWith('.kt'));assert(!seen.has(item.path));seen.add(item.path);const filename=path.resolve(item.filename);assert(filename.startsWith(path.join(REPO,'out')+path.sep));bytesTotal+=bytes.length;assert(bytesTotal<=256*1024*1024);if(item.bytes!==undefined)assert.equal(bytes.length,item.bytes);if(item.sha256!==undefined)assert.equal(sha256(bytes),item.sha256);assert(!CANDIDATE_FILES.some(name=>item.path===name||item.path.endsWith('/'+name)),'Existing excluded source reintroduced: '+item.path);
  if(item.path===TARGET){assert(!excludeTarget,'Native JS output original reintroduced');verifyFile(bytes,i.lock.target);}else{assert(!item.path.endsWith('/'+TARGET),'Native JS output replacement reintroduced');const text=bytes.toString(),view=lexicalReferenceView(text);for(const declaration of i.lock.declarations){const reasons=nativeOutputReferences(text,declaration,view);if(reasons.length)incoming.push({caller:item.path,declaration:declaration.name,reasons});}}
  assert(!filenames.has(filename),'Duplicate selected physical source');filenames.add(filename);assert(!SPLITS.some(rule=>item.path===rule.path),'Existing unsplit original reintroduced');sources.push({path:item.path,filename,...identity(bytes),source:bytes.toString('base64')});
 }}
 assert.deepEqual(incoming,[],'Actual selected native JS output consumer');if(!excludeTarget)assert.equal(sources.filter(pin=>pin.path===TARGET).length,1);
 const boundaries=i.lock.requiredBoundaries.map(pin=>{const selected=sources.filter(item=>item.path===pin.path||item.path.endsWith('/'+pin.path));assert.equal(selected.length,1,'Missing/duplicate genuine retained boundary: '+pin.path);return {originalPath:pin.path,...selected[0]};});
 const splitBoundaries=SPLITS.map((rule,index)=>{const selected=sources.filter(item=>item.path!==rule.path&&item.path.endsWith('/'+rule.path));assert.equal(selected.length,1,'Missing genuine existing split');assert.equal(selected[0].path,'compiler-port-backend-profile/'+rule.path);if(backendBinding)assert.equal(selected[0].filename,backendBinding.commonSources[index]);return {originalPath:rule.path,...selected[0]};});
 const actualSplits=new Map(splitBoundaries.map(pin=>[pin.originalPath,{text:Buffer.from(pin.source,'base64').toString(),removedDeclarations:i.splitTemplates.get(pin.originalPath).removedDeclarations}]));const existingProfileClosure=closedExistingProfile(i.candidates,actualSplits,new Map(sources.filter(pin=>!splitBoundaries.some(split=>split.path===pin.path)&&pin.path!==TARGET).map(pin=>[pin.path,{text:Buffer.from(pin.source,'base64').toString()}])));
 return {sources,inspectedFiles:sources.length,inspectedBytes:bytesTotal,inventorySha256:sha256(Buffer.from(JSON.stringify(sources.map(({source,...pin})=>pin)))),incoming,boundaries,splitBoundaries,existingProfileClosure};
}
export function nativeJsOutputReceiptFor(i,binding,selected){return {schemaVersion:1,kind:'wasm-unreachable-native-js-output-preparation',source:i.lock.source,sourceLockSha256:sha256(i.bytes),primaryClosureSha256:i.lock.primaryClosureSha256,tools:i.lock.tools,backendProfile:binding,target:i.lock.target,declarations:i.lock.declarations,memberAndLocalHeaders:i.lock.memberAndLocalHeaders,originalReference:{path:'original/'+TARGET,...identity(i.original),gitBlob:i.lock.target.gitBlob},primarySources:i.primaryInventory.length,primaryInventorySha256:sha256(Buffer.from(JSON.stringify(i.primaryInventory))),originalIncoming:i.originalIncoming,primaryIncoming:i.primaryIncoming,primaryExistingProfile:i.primaryExistingProfile,selection:{inspectedFiles:selected.inspectedFiles,inspectedBytes:selected.inspectedBytes,inventorySha256:selected.inventorySha256,incoming:selected.incoming,existingProfileClosure:selected.existingProfileClosure},retainedBoundaries:selected.boundaries,retainedSplits:selected.splitBoundaries,sourceSetExclusions:[TARGET],commonSources:[],scope:'Exactly one unreachable native JavaScript output file in the existing full-rebuild Wasm profile; required configuration/printer/lowerings stay selected.',limitation:'Conservative qualified/import/alias/wildcard/same-package source references including comments and strings; not a resolved IR graph or native filesystem port.',originalSourceUnmodified:true,existingProfileChanged:false,shippingFilesystemImplemented:false,compilerBuilt:false,languageReadiness:false};}
export function roots(sourceRoot,outputRoot){assert(outputRoot.startsWith(path.join(REPO,'out')+path.sep));assert(sourceRoot!==outputRoot&&!sourceRoot.startsWith(outputRoot+path.sep)&&!outputRoot.startsWith(sourceRoot+path.sep));}
async function pristineBackend(i,binding){for(const [index,filename]of binding.commonSources.entries())assert.deepEqual(identity(await readRegular(filename)),i.backend.splits[index].generated,'Existing profile input must be pristine at early preparation');}
export async function prepareNativeJsOutputProfile({sourceRoot,outputRoot,preparedBackendProfile,retainedSources}){
 sourceRoot=path.resolve(sourceRoot);outputRoot=path.resolve(outputRoot);roots(sourceRoot,outputRoot);await assertNoSymlink(outputRoot);const i=await inspectNativeJsOutputInputs(sourceRoot),binding=await bindNativeJsOutputBackend(i,preparedBackendProfile),selected=await inspectNativeJsOutputSelection(i,retainedSources,{backendBinding:binding}),receipt=nativeJsOutputReceiptFor(i,binding,selected);await pristineBackend(i,binding);
 const originalPath=path.join(outputRoot,receipt.originalReference.path);await mkdir(path.dirname(originalPath),{recursive:true,mode:0o700});await writeFile(originalPath,i.original,{flag:'wx',mode:0o600});const receiptPath=path.join(outputRoot,'native-js-output-inputs.json');await writeJson(receiptPath,receipt);return {commonSources:[],sourceSetExclusions:[TARGET],originalReferenceSources:[originalPath],receipt,receiptPath,receiptSha256:sha256(await readRegular(receiptPath))};
}
export async function verifyNativeJsOutputProfile(options){
 const {sourceRoot,outputRoot,preparedBackendProfile,retainedSources}=options;roots(path.resolve(sourceRoot),path.resolve(outputRoot));await assertNoSymlink(outputRoot);const i=await inspectNativeJsOutputInputs(sourceRoot),binding=await bindNativeJsOutputBackend(i,preparedBackendProfile),selected=await inspectNativeJsOutputSelection(i,retainedSources,{backendBinding:binding}),expected=nativeJsOutputReceiptFor(i,binding,selected);await pristineBackend(i,binding);assert.equal(path.resolve(options.receiptPath),path.join(path.resolve(outputRoot),'native-js-output-inputs.json'));assert.deepEqual(JSON.parse(await readRegular(options.receiptPath)),expected);verifyFile(await readRegular(path.join(outputRoot,expected.originalReference.path)),expected.originalReference);return expected;
}
