import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {readRegular,verifyFile,writeJson} from '../../scripts/source.mjs';import {prepareBackendSources} from '../backend/prepare.mjs';import {prepareBackendProfileSources,verifyBackendProfilePreparation} from '../backend-profile/prepare.mjs';import {normalizeRecordedImports} from '../serializer-output-bindings/transform.mjs';import {reconstructModuleRequirePathPredecessorSelection} from '../module-relative-paths/prepare.mjs';
import {prepareNativeJsOutputProfile,verifyNativeJsOutputProfile,readNativeJsOutputLock,TARGET,FRAGMENT,identity} from './prepare.mjs';import {verifyNativeJsOutputFinalSources} from './final.mjs';
const HERE=path.dirname(fileURLToPath(import.meta.url)),REPO=path.resolve(HERE,'../../../..'),ASSERT_IMPORT='org.jetbrains.kotlin.portable.assertions.compilerAssert as assert';
export async function makeNativeOutputFixture(prefix='run-'){
 const parent=path.join(REPO,'out/kotlin-native-js-output-profile');await mkdir(parent,{recursive:true,mode:0o700});const outputRoot=await mkdtemp(path.join(parent,prefix)),sourceRoot=path.join(REPO,'out/kotlin-compiler-port/sources');
 const evidencePath=path.join(REPO,'out/kotlin-compiler-port/builds/path-comment-copy-whole-1791650935962697955/compiler-build-receipt.json'),evidenceBytes=await readRegular(evidencePath,32*1024*1024),evidence=JSON.parse(evidenceBytes);assert.equal(evidence.status,'failed');const baseline=evidence.sourceMapPathFinalReceipt.inspected;assert.equal(baseline.length,3525);const allowedAddedImports=evidence.sourceMapPathFinalReceipt.allowedAddedImports,propertyImports=allowedAddedImports.filter(name=>!['kotlin.jvm.*',ASSERT_IMPORT].includes(name));
 for(let offset=0;offset<baseline.length;offset+=24){const batch=await Promise.allSettled(baseline.slice(offset,offset+24).map(async item=>assert.deepEqual(identity(await readRegular(item.filename)),{bytes:item.bytes,sha256:item.sha256})));for(const result of batch)if(result.status!=='fulfilled')throw result.reason;}
 const moduleFixturePath=path.join(REPO,'out/kotlin-module-relative-paths-selection-1791651688699596846/fixture.json'),moduleFixtureBytes=await readRegular(moduleFixturePath,32*1024*1024),module=JSON.parse(moduleFixtureBytes),moduleLock=JSON.parse(await readRegular(path.join(HERE,'../module-relative-paths/sources.lock.json')));assert.deepEqual(propertyImports,moduleLock.recordedPropertyImports);
 const lock=(await readNativeJsOutputLock()).lock,lateBoundaryBytes=new Map(),actual=[],initial=[];
 // The early twenty-one boundaries are genuine primary bytes, not already
 // transformed late files. Only private copies are changed after early verify.
 for(const item of baseline){const required=lock.requiredBoundaries.find(pin=>item.path===pin.path||item.path.endsWith('/'+pin.path));if(required){const filename=path.join(outputRoot,'boundaries',item.path),original=verifyFile(await readRegular(path.join(sourceRoot,required.path)),required);await mkdir(path.dirname(filename),{recursive:true,mode:0o700});await writeFile(filename,original,{flag:'wx',mode:0o600});initial.push({path:item.path,filename,...identity(original)});actual.push({path:item.path,filename});lateBoundaryBytes.set(filename,await readRegular(item.filename));}else{initial.push(item);actual.push(item);}}
 const backend=await prepareBackendSources({sourceRoot,outputRoot:path.join(outputRoot,'backend')}),backendSources=new Map(backend.receipt.sources.map((pin,index)=>[pin.path,backend.commonSources[index]]));
 const earlyBase=initial.map(item=>backendSources.has(item.path)?{path:item.path,filename:backendSources.get(item.path)}:item.path===TARGET?{path:item.path,filename:path.join(sourceRoot,TARGET)}:item),browserEntry=baseline.find(item=>item.path==='compiler-port-entry/BrowserCompilerPipeline.kt').filename;
 const backendProfile=await prepareBackendProfileSources({sourceRoot,outputRoot:path.join(outputRoot,'backend-profile'),preparedBackend:backend,browserEntry,retainedSources:earlyBase.map(item=>item.filename)});assert.deepEqual((await verifyBackendProfilePreparation(path.dirname(backendProfile.receiptPath))).receipt,backendProfile.receipt);
 const splitSources=new Map(backendProfile.receipt.files.map((pin,index)=>['compiler-port-backend-profile/'+pin.path,backendProfile.commonSources[index]])),earlySources=earlyBase.map(item=>splitSources.has(item.path)?{path:item.path,filename:splitSources.get(item.path)}:item),preparationOptions={sourceRoot,outputRoot:path.join(outputRoot,'native-profile'),preparedBackendProfile:backendProfile,retainedSources:earlySources};
 const preparedProfile=await prepareNativeJsOutputProfile(preparationOptions);await verifyNativeJsOutputProfile({...preparationOptions,receiptPath:preparedProfile.receiptPath});
 for(const [filename,bytes]of lateBoundaryBytes)await writeFile(filename,bytes);
 // Verify the completed graph's four comment outputs against the genuine sealed
 // module predecessor before adopting its canonical owners. No old file changes.
 const commentGrafts=[];for(const pin of module.options.preparedCommentTypeNames.receipt.files){const prior=baseline.find(item=>item.path===pin.path);assert(prior);verifyFile(normalizeRecordedImports(await readRegular(prior.filename),propertyImports),pin);const canonical=module.options.preparedCommentTypeNames.commonSources.find(filename=>filename===path.join(module.options.preparedCommentTypeNames.outputRoot,pin.path));assert(canonical);verifyFile(normalizeRecordedImports(await readRegular(canonical),propertyImports),pin);commentGrafts.push({path:pin.path,from:prior.filename,to:canonical,canonical:pin});}
 let finalSources=actual.filter(item=>item.path!==TARGET).map(item=>{const graft=commentGrafts.find(pin=>pin.path===item.path);return graft?{path:item.path,filename:graft.to}:item;});
 for(const pin of module.prepared.receipt.files){const selected={path:pin.path,filename:path.join(module.options.outputRoot,pin.path)};if(pin.path===FRAGMENT)finalSources=finalSources.map(item=>item.path===FRAGMENT?selected:item);else{assert(!finalSources.some(item=>item.path===pin.path));finalSources.push(selected);}}
 finalSources=await Promise.all(finalSources.map(async item=>({...item,...identity(await readRegular(item.filename))})));
 const moduleFinal=await reconstructModuleRequirePathPredecessorSelection({...module.options,retainedSources:finalSources});assert.equal(moduleFinal.actualFinalSources,3525);
 const finalOptions={...preparationOptions,receiptPath:preparedProfile.receiptPath,preparedProfile,retainedSources:finalSources,allowedAddedImports,verifiedModuleBoundary:{outputRoot:module.options.outputRoot,final:moduleFinal}},final=await verifyNativeJsOutputFinalSources(finalOptions);assert.equal(final.receipt.inspectedFiles,3525);assert.equal(final.receipt.retainedBoundaryBindings.length,21);assert.equal(final.receipt.existingSplitBindings.length,4);
 await writeJson(path.join(outputRoot,'actual-selected-before.json'),baseline);await writeJson(path.join(outputRoot,'actual-selected-after.json'),finalSources);await writeJson(path.join(outputRoot,'module-final.json'),moduleFinal);const baselineEvidence={filename:evidencePath,...identity(evidenceBytes)},moduleFixtureEvidence={filename:moduleFixturePath,...identity(moduleFixtureBytes)};
 await writeJson(path.join(outputRoot,'fixture.json'),{sourceRoot,outputRoot,preparationOptions,preparedProfile,finalOptions,baselineEvidence,moduleFixtureEvidence,commentGrafts,originalBackendProfileRebuilt:true,oldBackendProfileVerifierExecuted:true,compilerSucceeded:false});return {outputRoot,sourceRoot,preparedProfile,preparationOptions,finalOptions,final,backendProfile,baselineEvidence,moduleFixtureEvidence,commentGrafts};
}
export async function runNativeOutputProbe(){const fixture=await makeNativeOutputFixture(),i=fixture.preparedProfile.receipt,receipt={schemaVersion:1,kind:'genuine-one-file-native-js-output-source-profile',source:i.source,sourceLockSha256:i.sourceLockSha256,baselineEvidence:fixture.baselineEvidence,moduleFixtureEvidence:fixture.moduleFixtureEvidence,preparation:i,finalSelection:fixture.final.receipt,originalSources:i.primarySources,originalIncoming:i.originalIncoming,retainedIncoming:i.primaryIncoming,actualEarlyInputs:i.selection.inspectedFiles,actualFinalInputs:fixture.final.receipt.inspectedFiles,trueEarlyPrimaryBoundaries:21,verifiedLateModuleBoundary:true,verifiedCommentOwnerGrafts:fixture.commentGrafts,originalBackendProfileRebuilt:true,oldBackendProfileVerifierExecuted:true,additionalExclusions:1,unchangedPriorExclusions:21,unchangedLogicalSplits:4,requiredBoundaryCount:21,requiredOriginalBoundaryCount:19,additionalGenuineTypeCount:2,newJvmOrWasmRuntimeExecuted:false,filesystemImplemented:false,fullCompilerBuilt:false,languageReadiness:false};await writeJson(path.join(fixture.outputRoot,'receipt.json'),receipt);console.log(JSON.stringify({outputRoot:fixture.outputRoot,originalSources:receipt.originalSources,early:receipt.actualEarlyInputs,final:receipt.actualFinalInputs,additionalExclusions:1,retainedBoundaries:21,originalIncoming:receipt.originalIncoming.length,remainingIncoming:0,fullCompilerBuilt:false}));}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))await runNativeOutputProbe();
