import assert from 'node:assert/strict';import path from 'node:path';import {fileURLToPath} from 'node:url';import {readdir,lstat} from 'node:fs/promises';
import {readRegular,sha256,verifyFile,assertNoSymlink} from '../../scripts/source.mjs';import {readNativeJsOutputLock} from './prepare.mjs';
const HERE=path.dirname(fileURLToPath(import.meta.url)),REPO=path.resolve(HERE,'../../../..');
async function files(root){const result=[];for(const entry of await readdir(root,{withFileTypes:true})){const p=path.join(root,entry.name);assert(!entry.isSymbolicLink());if(entry.isDirectory())result.push(...await files(p));else{assert(entry.isFile());result.push(p);}}return result.sort();}
async function content(pin){const bytes=await readRegular(pin.path,32*1024*1024);assert.deepEqual({bytes:bytes.length,sha256:sha256(bytes)},{bytes:pin.bytes,sha256:pin.sha256});return bytes;}
export async function verifyNativeJsOutputEvidence(){
 const i=await readNativeJsOutputLock(),evidence=JSON.parse(await readRegular(path.join(HERE,'evidence/receipt.json'),32*1024*1024));assert.equal(evidence.sourceLockSha256,sha256(i.bytes));assert.deepEqual(evidence.source,i.lock.source);
 assert.equal(evidence.additionalExclusions,1);assert.equal(evidence.unchangedPriorExclusions,21);assert.equal(evidence.unchangedLogicalSplits,4);assert.equal(evidence.requiredBoundaryCount,21);assert.equal(evidence.requiredOriginalBoundaryCount,19);assert.equal(evidence.additionalGenuineTypeCount,2);assert.equal(evidence.originalSources,3417);assert.equal(evidence.actualEarlyInputs,3525);assert.equal(evidence.actualFinalInputs,3525);
 for(const field of ['filesystemImplemented','fullCompilerBuilt','languageReadiness','newJvmOrWasmRuntimeExecuted'])assert.equal(evidence[field],false);
 assert.deepEqual(evidence.executions.map(run=>run.phase),['final-check','final-guards']);
 for(const run of evidence.executions){assert.equal(run.exitCode,0);const status=JSON.parse(await content(run.statusPin));assert.equal(status.exitCode,0);assert.equal(run.statusPin.path,run.status);assert.equal(run.logPin.path,run.log);await content(run.logPin);await assertNoSymlink(run.outputRoot);assert(run.outputRoot.startsWith(path.join(REPO,'out/kotlin-native-js-output-profile')+path.sep));assert.deepEqual(run.artifacts.map(pin=>pin.path).sort(),await files(run.outputRoot));for(const pin of run.artifacts)await content(pin);}
 const check=evidence.executions[0],result=JSON.parse(await readRegular(path.join(check.outputRoot,'receipt.json')));for(const [key,value]of Object.entries(result))assert.deepEqual(evidence[key],value,'Sealed check field mismatch: '+key);
 assert.deepEqual(evidence.unitFiles.map(pin=>pin.path).sort(),['README.md','references.mjs','prepare.mjs','final.mjs','update-recipe.mjs','probe.mjs','guards.mjs','verify.mjs','sources.lock.json'].sort());for(const pin of evidence.unitFiles)verifyFile(await readRegular(path.join(HERE,pin.path)),pin);
 const integrityBytes=await readRegular(path.join(HERE,'evidence/integrity.json'));assert.deepEqual({bytes:integrityBytes.length,sha256:sha256(integrityBytes)},{bytes:evidence.integrityPin.bytes,sha256:evidence.integrityPin.sha256});const integrity=JSON.parse(integrityBytes),rawGuards=JSON.parse(await readRegular(path.join(evidence.executions[1].outputRoot,'guards.json')));assert.deepEqual(integrity,rawGuards);assert.equal(integrity.guards,37);assert.equal(integrity.skipped,0);assert.equal(integrity.allRejected,true);assert.equal(integrity.restoredFinalPassed,true);assert.equal(integrity.records.length,37);assert.equal(new Set(integrity.records.map(row=>row.name)).size,37);assert(integrity.records.every(row=>row.rejected&&row.error?.name&&row.error?.message));
 for(const name of ['false-compiler-built','receipt-source-identity','forged-prior-policy','module-proof-not-canonical'])assert(integrity.records.find(row=>row.name===name)?.assertionTarget?.field);assert.equal(integrity.eachRejectionMatchedExpectedReason,true);assert.equal(integrity.uniqueFinalOutputRoots,true);assert(evidence.retainedInitialProof.negativeRunInvalidated);assert.equal(evidence.retainedInitialProof.executions[1].exitCode,1);assert.equal(evidence.retainedInitialProof.executions[0].exitCode,0);for(const pin of evidence.referencePins)await content(pin);for(const run of evidence.retainedInitialProof.executions){assert.equal(JSON.parse(await content(run.statusPin)).exitCode,run.exitCode);await content(run.logPin);for(const pin of run.artifacts)await content(pin);}for(const pin of evidence.retainedInitialProof.codeSnapshot)await content(pin);assert.equal(evidence.retainedIntermediateCheck.execution.exitCode,-15);assert.equal(JSON.parse(await content(evidence.retainedIntermediateCheck.execution.statusPin)).exitCode,-15);await content(evidence.retainedIntermediateCheck.execution.logPin);for(const pin of evidence.retainedIntermediateCheck.execution.artifacts)await content(pin);for(const pin of evidence.retainedIntermediateCheck.codeSnapshot)await content(pin);
 return {artifacts:evidence.executions.reduce((sum,run)=>sum+run.artifacts.length,0),localPins:evidence.unitFiles.length,primarySources:evidence.originalSources,early:evidence.actualEarlyInputs,final:evidence.actualFinalInputs,guards:integrity.guards};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify(await verifyNativeJsOutputEvidence()));
