import assert from 'node:assert/strict';import {mkdir,mkdtemp,symlink,writeFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {prepareAstIntegerConsumer} from '../integer/prepare.mjs';import {prepareAstIntegerBounds} from '../integer-bounds/prepare.mjs';import {prepareJsAstInput} from '../input-codec/prepare.mjs';
import {prepareJsAstDeserializer,verifyJsAstDeserializer,auditCommentConsumers} from './prepare.mjs';
const HERE=path.dirname(fileURLToPath(import.meta.url)),REPO=path.resolve(HERE,'../../../../..'),sourceRoot=path.join(REPO,'out/kotlin-compiler-port/sources');
await mkdir(path.join(REPO,'out/kotlin-js-ast-deserializer'),{recursive:true});const root=await mkdtemp(path.join(REPO,'out/kotlin-js-ast-deserializer/guards-'));
const preparedInteger=await prepareAstIntegerConsumer({sourceRoot,outputRoot:path.join(root,'integer')}),preparedBounds=await prepareAstIntegerBounds({sourceRoot,outputRoot:path.join(root,'bounds'),preparedInteger}),preparedInput=await prepareJsAstInput({sourceRoot,outputRoot:path.join(root,'input')});
let passed=0;async function test(name,body){await body();passed++;console.log('PASS '+name);}async function fixture(name){const options={sourceRoot,outputRoot:path.join(root,name),preparedInteger,preparedBounds,preparedInput};return {...options,...await prepareJsAstDeserializer(options)};}
await test('Exact consumer preparation verifies',async()=>verifyJsAstDeserializer(await fixture('exact')));
await test('Changed caller code rejected',async()=>{const f=await fixture('caller');await writeFile(f.commonSources[0],'// modified');await assert.rejects(verifyJsAstDeserializer(f));});
await test('Changed comment factory rejected',async()=>{const f=await fixture('factory');await writeFile(f.commonSources[1],'// modified');await assert.rejects(verifyJsAstDeserializer(f));});
await test('False complete-deserializer claim rejected',async()=>{const f=await fixture('claim');f.receipt.fullDeserializerBuilt=true;await writeFile(f.receiptPath,JSON.stringify(f.receipt));await assert.rejects(verifyJsAstDeserializer(f));});
await test('False global singleton identity claim rejected',async()=>{const f=await fixture('identity');f.receipt.globalEmptyListIdentityPreserved=true;await writeFile(f.receiptPath,JSON.stringify(f.receipt));await assert.rejects(verifyJsAstDeserializer(f));});
await test('Changed predecessor bytes rejected',async()=>{const bytes=await import('node:fs/promises').then(m=>m.readFile(preparedBounds.commonSources[0]));await writeFile(preparedBounds.commonSources[0],'// changed');await assert.rejects(fixture('badpredecessor'));await writeFile(preparedBounds.commonSources[0],bytes);});
await test('Existing output rejected',async()=>{const f=await fixture('existing');await assert.rejects(prepareJsAstDeserializer(f));});
await test('Symlink output rejected',async()=>{const target=path.join(root,'target');await mkdir(target);const outputRoot=path.join(root,'link');await symlink(target,outputRoot);await assert.rejects(prepareJsAstDeserializer({sourceRoot,outputRoot,preparedInteger,preparedBounds,preparedInput}));});
await test('New global singleton consumer rejected',async()=>{const file=path.join(root,'GlobalConsumer.kt');await writeFile(file,'val flag = node.commentsBeforeNode === emptyList<JsComment>()');await assert.rejects(auditCommentConsumers([{path:'GlobalConsumer.kt',filename:file}]));});
await test('New undocumented selected consumer rejected',async()=>{const file=path.join(root,'UnknownConsumer.kt');await writeFile(file,'fun use(node: JsNode) = node.commentsBeforeNode');await assert.rejects(auditCommentConsumers([{path:'UnknownConsumer.kt',filename:file}]));});
console.log(JSON.stringify({passed,failed:0,skipped:0,output:root}));
