import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

const RUNTIME_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('documents the Swift registration checklist and required verification gates', async () => {
	const readme = await readFile(path.join(RUNTIME_ROOT, 'README.md'), 'utf8');

	for (const requiredText of [
		'## Registration checklist',
		'pnpm run package:wasm-swift',
		'--source-dir path/to/raw-swift-runtime',
		'--source "upstream/build provenance"',
		'`--source` is required for every packaged dist',
		'The package source may already store large compiler modules as gzip-only',
		'package metadata still records the logical `swiftc.wasm`',
		'Its text output and optional JSON receipt include next actions',
		'continue with the source build flow instead of packaging the SDK zip',
		'SwiftWasm `.artifactbundle.zip` SDK release files are rejected',
		'--browser-contract',
		'metadata records the Swift browser runtime contract',
		'pnpm run sync:wasm-swift runtime/swift/dist static/wasm-swift',
		'pnpm run package-sync:wasm-swift-from-plan',
		'pnpm run package-sync:wasm-swift-from-plan:strict',
		'--require-upstream-baseline-receipt',
		'--require-browser-compiler-contracts',
		'--require-browser-build-command',
		'--require-browser-build-execution',
		'--require-browser-build-log',
		'--workflow-preflight-receipt',
		'--compress-static',
		'--readiness',
		'--readiness-require-browser-build-command-provenance',
		'--readiness-require-browser-build-execution-provenance',
		'--readiness-require-browser-build-log-provenance',
		'--readiness-require-upstream-baseline-provenance',
		'--readiness-require-compressed-manifest',
		'--readiness-browser-contract',
		'The lower-level `package-sync:wasm-swift-from-plan` command accepts the same `--readiness-*` flags',
		'pnpm run import-sync:wasm-swift:strict',
		'pnpm run promote:wasm-swift',
		'--dry-run-registration',
		'then runs',
		'`apply:wasm-swift-registration`',
		'--prefer-descriptor-archive-file',
		'--input-descriptor path/to/wasm-swift-runtime/wasm-swift-<fingerprint>.tar.gz.json',
		'descriptor imports use the recorded URL first',
		'workflow preflight receipt',
		'workflow-preflight.snapshot.json',
		'wasm-swift-workflow-preflight.json',
		'preserving the dispatch inputs, normalized paths, disk probe',
		'Use the lower-level `import-sync:wasm-swift` script instead of the strict shortcut',
		'syncs and compresses into a staging target first',
		'publishes to `static/wasm-swift` only after readiness passes',
		'raw file bundles are rejected',
		'unprovenanced bundles are rejected',
		'Descriptor imports verify `archiveSha256` before unpacking',
		'verify `runtimeBuildSha256` against the imported `runtime-build.json`',
		'read the descriptor\'s sibling',
		'gzip-only `swiftc.wasm.gz` and',
		'`swiftpm.wasm.gz` files',
		'validated against the decompressed wasm',
		'fingerprint, runtime contract, or file-list metadata with the packaged manifest',
		'mismatches',
		'including descriptor fingerprint',
		'--require-descriptor-metadata',
		'The root `import-sync:wasm-swift:strict` shortcut enables `--require-descriptor-metadata`',
		'direct sync CLI accepts only optional `sourceDir` and `targetDir`',
		'single-line and multi-line `readLine()` stdin',
		'The current contract',
		'snapshot uses `version: 2`',
		'older `browserCompilerBuild.runtimeContract`',
		'runtime/swift/dist/runtime-build.json',
		'runtime-build.json',
		'wasm-swift-runtime-build-v1',
		'"runtimeContract"',
		'wasm-swift-runtime-contract-v1',
		'"version": 2',
		'manifest is',
		'also stamped with the Swift browser `runtimeContract`',
		'runnerWorker',
		'compilerWasm',
		'packageManagerWasm',
		'sdkArchive',
		'invalid Swift source reports a',
		'validates the packaged manifest and `runtime-build.json` provenance',
		'--timeout-ms <positive-integer>',
		'When no browser compiler build outputs exist yet',
		'Keep `--source-root`, `--checkout-root`, `--build-dir`, and later `--plan` paths on that',
		'--execute-browser-build-command',
		'--discover-build-outputs',
		'pnpm --dir runtime/swift run probe:toolchain',
		'pnpm --dir runtime/swift run probe:install',
		'--probe-toolchain',
		'--probe-toolchain-run-wasm',
		'browser_build_command` is required',
		'pnpm run export:wasm-swift:strict',
		'--require-build-plan-provenance',
		'--require-browser-build-command-provenance',
		'--require-browser-build-execution-provenance',
		'--require-browser-build-log-provenance',
		'--browser-build-log',
		'export:wasm-swift:strict',
		'pnpm run doctor:wasm-swift:probe',
		'pnpm run doctor:wasm-swift:probe-run',
		'pnpm run compress:static-runtimes',
		'pnpm run doctor:wasm-swift:candidate',
		'candidate doctor before',
		'does not require `SWIFT` registration yet',
		'pnpm run doctor:wasm-swift:strict',
		'the strict doctor adds the same registration checks',
		'Before registering `SWIFT` in the playground, run the candidate readiness gate',
		'pnpm run verify:wasm-swift-candidate',
		'does not require `SWIFT` registration yet',
		'browser build command provenance',
		'browser build execution provenance',
		'source bootstrap receipt provenance',
		'It is the gate for proving a real Swift bundle',
		'pnpm run plan:wasm-swift-registration',
		'lists every app file and',
		'metadata surface that must be changed for registration',
		'After registering `SWIFT` in the playground, run the final readiness gate',
		'pnpm run verify:wasm-swift-readiness',
		'requires `runtime-build.json` source provenance to match the manifest',
		'verifies any recorded `wasmSdkChecksum` against the bundled `sdk.tar.gz` bytes',
		're-reads the recorded build plan and upstream baseline receipt files',
		'contract/status metadata',
		'browserCompilerBuild.command',
		'browserCompilerBuild.execution',
		'browser build log',
		'browser-build.snapshot.log',
		'browserCompilerBuild.requiredOutputs',
		'browserCompilerBuild.runtimeContract',
		'stale browser worker contracts',
		'current `browserCompilerBuild.runtimeContract`',
		'snapshot to match',
		'wasm-idle-swift-upstream-baseline-build-v1',
		'verified build plan with source',
		'source bootstrap receipt',
		'recorded browser compiler build command provenance',
		'a passed browser compiler build execution receipt',
		'a passed upstream baseline receipt',
		'a passing browser runtime contract',
		'passes before the registration change',
		'not ready to expose',
		'packages/core/src/languages.ts',
		'WasmIdleLanguageId',
		'supportedLanguageIds',
		'DEFAULT_DEFERRED_PROGRESS_LANGUAGES',
		'src/lib/playground/index.ts',
		'src/routes/language-registry.ts',
		'scripts/support-matrix.mjs',
		'support matrix',
		'src/lib/playground/core-language-contract.test.ts',
		'src/lib/playground/index.test.ts',
		'src/routes/language-registry.test.ts'
	]) {
		assert.match(readme, new RegExp(requiredText.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&'), 'u'));
	}
});
