#!/usr/bin/env node
import assert from 'node:assert/strict';import {execFile} from 'node:child_process';import {mkdir,mkdtemp,readdir,writeFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import {promisify} from 'node:util';
import {readRegular,sha256,verifyFile,writeJson} from '../../scripts/source.mjs';import {verifyBootstrap} from '../../build/bootstrap.mjs';
import {verifyEvidence} from '../js-ast/verify.mjs';import {observeAstInChromium} from '../js-ast/browser.mjs';
import {prepareConstantsArithmetic,verifyConstantsArithmetic,auditIncomingIntegerCallers} from './prepare.mjs';import {checkerBody,checkerProjection} from './extract.mjs';
const HERE=path.dirname(fileURLToPath(import.meta.url)),REPO=path.resolve(HERE,'../../../..'),sourceRoot=path.join(REPO,'out/kotlin-compiler-port/sources');
const lockBytes=await readRegular(path.join(HERE,'sources.lock.json')),lock=JSON.parse(lockBytes);await mkdir(path.join(REPO,'out/kotlin-constants-arithmetic'),{recursive:true,mode:0o700});
const output=await mkdtemp(path.join(REPO,'out/kotlin-constants-arithmetic/run-')),local=name=>path.join(output,name);
const prepared=await prepareConstantsArithmetic({sourceRoot,outputRoot:local('binding')});await verifyConstantsArithmetic({sourceRoot,outputRoot:local('binding'),receiptPath:prepared.receiptPath});
const astReceipt=JSON.parse(await readRegular(path.join(HERE,'../js-ast/evidence/receipt.json')));await verifyEvidence(astReceipt,{artifactRoot:path.join(REPO,'out/kotlin-js-ast/differential-WViAyC')});
const astInteger=path.join(HERE,'../js-ast',lock.astIntegerSource.path);verifyFile(await readRegular(astInteger),lock.astIntegerSource);
for(const kind of ['original','common']){const bytes=await readRegular(kind==='original'?path.join(sourceRoot,lock.sources[0].path):prepared.commonSources[0]);assert.equal(sha256(Buffer.from(checkerBody(bytes))),lock.checkerSha256);await writeFile(local(kind+'-Checker.kt'),checkerProjection(bytes,kind==='common'),{flag:'wx',mode:0o600});}
await writeFile(local('CompileTimeType.kt'),verifyFile(await readRegular(path.join(sourceRoot,lock.sources[1].path)),lock.sources[1]),{flag:'wx',mode:0o600});
for(const pin of lock.observers)await writeFile(local(pin.path),verifyFile(await readRegular(path.join(HERE,pin.path)),pin),{flag:'wx',mode:0o600});
const wholeRoot=path.join(REPO,'out/kotlin-compiler-port/builds/common-boundaries-whole-1791635510943341799'),wholeBytes=await readRegular(path.join(wholeRoot,'compiler-build-receipt.json')),whole=JSON.parse(wholeBytes),argsBytes=await readRegular(path.join(wholeRoot,'compiler-klib.args'));
const args=argsBytes.toString().split('\n').filter(Boolean).map(line=>line.startsWith('"')?JSON.parse(line):line),sourceFiles=args.filter(x=>!x.startsWith('-')&&x.endsWith('.kt'));assert.equal(sourceFiles.length,whole.compileSources.length);
const retainedSources=whole.compileSources.map(pin=>{const matches=sourceFiles.filter(p=>p.endsWith('/'+pin.path));assert.equal(matches.length,1,pin.path);return {path:pin.path,filename:matches[0]};});
const incoming=await auditIncomingIntegerCallers(retainedSources);
const bootstrap=await verifyBootstrap(),stdlib=bootstrap.artifacts.find(p=>p.id==='stdlib-jvm').path,flagsBytes=await readRegular(path.join(HERE,'../build-flags.json')),flags=JSON.parse(flagsBytes);
const run=promisify(execFile),commands=[];async function execute(phase,bin,args){console.log('phase: '+phase);const r=await run(bin,args,{timeout:240000,maxBuffer:32*1024*1024,encoding:'utf8'});if(r.stderr)process.stderr.write(r.stderr);commands.push({phase,command:[bin,...args],exitCode:0});return r.stdout;}
const java=['-Xmx768m','-cp',bootstrap.classPath],jvm=[...java,'org.jetbrains.kotlin.cli.jvm.K2JVMCompiler','-no-stdlib','-no-reflect','-jvm-target','17','-language-version',flags.languageVersion,'-api-version',flags.apiVersion,...flags.compilerFlags,'-classpath',stdlib],shared=[local('CompileTimeType.kt'),local('Probe.kt')];
await execute('genuine-generated-checker-jvm-build','java',[...jvm,'-d',local('original.jar'),local('original-Checker.kt'),...shared,local('OriginalSupport.kt'),local('JvmEntry.kt')]);
const common=[prepared.commonSources[1],astInteger,local('common-Checker.kt'),...shared,local('CommonSupport.kt')];
await execute('common-arithmetic-checker-jvm-build','java',[...jvm,'-d',local('portable.jar'),...common,local('JvmEntry.kt')]);
async function observe(name){return JSON.parse(await execute(name+'-observe','java',['-ea','-cp',[local(name==='original'?'original.jar':'portable.jar'),stdlib].join(path.delimiter),'org.jetbrains.kotlin.constantsprobe.JvmEntryKt']));}
const original=await observe('original'),portable=await observe('common');await writeJson(local('original-jvm.json'),original);await writeJson(local('portable-jvm.json'),portable);assert.deepEqual(portable.records,original.records);
await mkdir(local('klib'));await mkdir(local('wasm'));const wasm=[...java,'org.jetbrains.kotlin.cli.js.KotlinWasmCompiler','-Xwasm-target=wasm-js','-language-version',flags.languageVersion,'-api-version',flags.apiVersion,...flags.compilerFlags,'-libraries',bootstrap.wasmJsStdlib];
await execute('common-arithmetic-wasm-klib','java',[...wasm,'-Xmulti-platform','-Xcommon-sources='+common.join(','),'-ir-output-dir',local('klib'),'-ir-output-name','arithmetic',...common,local('WasmEntry.kt')]);
await execute('common-arithmetic-wasm-module','java',[...wasm,'-Xir-produce-js','-Xinclude='+local('klib/arithmetic.klib'),'-ir-output-dir',local('wasm'),'-ir-output-name','js-ast','-main','noCall','-Xwasm-enable-array-range-checks','-Xwasm-enable-asserts']);
const node=JSON.parse(await execute('common-arithmetic-node-observe',process.execPath,['--experimental-wasm-exnref','--input-type=module','-e','const m=await import(process.argv[1]);console.log(m.astProbeJson());',pathToFileURL(local('wasm/js-ast.mjs')).href]));await writeJson(local('portable-wasm.json'),node);assert.deepEqual(node.records,original.records);
const browser=await observeAstInChromium(output,original.records);await writeFile(local('portable-chromium.json'),browser.raw,{flag:'wx',mode:0o600});assert.deepEqual(node.rawIdentity,browser.observation.rawIdentity);assert.notDeepEqual(original.rawIdentity,portable.rawIdentity);
const outputs=[];async function collect(dir){for(const item of await readdir(local(dir),{withFileTypes:true})){const name=dir?dir+'/'+item.name:item.name;if(item.isDirectory())await collect(name);else{const b=await readRegular(local(name));outputs.push({path:name,bytes:b.length,sha256:sha256(b)});}}}await collect('');
const receipt={schemaVersion:1,kind:'genuine-generated-constants-arithmetic-jdk-common-profile',source:lock.source,sourceLockSha256:sha256(lockBytes),checkToolSha256:sha256(await readRegular(fileURLToPath(import.meta.url))),buildFlagsSha256:sha256(flagsBytes),preparation:prepared.receipt,
    checkerProjection:{sha256:lock.checkerSha256,bodyUnchanged:true,enumUnchanged:true,scope:'Full genuine checkBinaryOp and14 genuine CompileTimeType entries, isolated from other unchanged generated functions and CallableId.'},
    incomingCallerAudit:{selectedSourceCount:sourceFiles.length,wholeReceiptSha256:sha256(wholeBytes),argsSha256:sha256(argsBytes),incoming,identitySensitiveIncoming:[]},
    comparison:{observations:original.records.length,originalJvmEqualsCommonJvm:true,originalJvmEqualsNodeWasm:true,originalJvmEqualsOfflineChromium:true,skipped:0,recordsSha256:sha256(Buffer.from(JSON.stringify(original.records)))},
    commands,outputs,rawFailures:{originalJvm:original.failures,commonJvm:portable.failures,nodeWasm:node.failures,offlineChromium:browser.observation.failures},
    rawIdentityBoundary:{originalJvm:original.rawIdentity,commonJvm:portable.rawIdentity,nodeWasm:node.rawIdentity,offlineChromium:browser.observation.rawIdentity,equal:false,contract:'Value/byte/compare/hash equality is tested. No arbitrary JDK valueOf or arithmetic-result cached-object identity claim; actual incoming checker caller audit is empty in this frozen selection.'},
    algorithmCosts:'Base256 addition/subtraction/bitwise O(n+m); schoolbook multiplication and binary long division O(n*m) with base256 bit factor8, linear live digit storage. Canonical decimal formatting inherited AstInteger has its own repeated-division cost. No benchmark/full-FIR performance claim.',
    bounds:'Magnitude precision is not reduced to machine integers. Backend arrays have Int-indexed addressability and host memory limits; checked length arithmetic rejects unaddressable arrays before allocation. Differential corpus up to128 input bytes, not maximal-memory acceptance.',
    browser:browser.receipt,cachedJdkObjectIdentityClaimed:false,fullGeneratedMapBuilt:false,fullCompilerBuilt:false,languageReadiness:false};
await writeJson(local('receipt.json'),receipt);console.log(JSON.stringify({output,comparison:receipt.comparison,incomingCallers:incoming.length,rawIdentityEqual:false}));
