import assert from 'node:assert/strict';import {mkdir,mkdtemp,symlink,writeFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {prepareConstantsArithmetic,verifyConstantsArithmetic,auditIncomingIntegerCallers} from './prepare.mjs';
const HERE=path.dirname(fileURLToPath(import.meta.url)),REPO=path.resolve(HERE,'../../../..'),sourceRoot=path.join(REPO,'out/kotlin-compiler-port/sources');await mkdir(path.join(REPO,'out/kotlin-constants-arithmetic'),{recursive:true});const root=await mkdtemp(path.join(REPO,'out/kotlin-constants-arithmetic/guards-'));let passed=0;
async function test(name,body){await body();passed++;console.log('PASS '+name);}async function fixture(name){const options={sourceRoot,outputRoot:path.join(root,name)};return {...options,...await prepareConstantsArithmetic(options)};}
await test('Exact arithmetic preparation verifies',async()=>verifyConstantsArithmetic(await fixture('exact')));
await test('Changed generated body rejected',async()=>{const f=await fixture('body');await writeFile(f.commonSources[0],'// changed');await assert.rejects(verifyConstantsArithmetic(f));});
await test('Changed arithmetic implementation rejected',async()=>{const f=await fixture('integer');await writeFile(f.commonSources[1],'// changed');await assert.rejects(verifyConstantsArithmetic(f));});
await test('False full generated map claim rejected',async()=>{const f=await fixture('claim');f.receipt.fullGeneratedMapBuilt=true;await writeFile(f.receiptPath,JSON.stringify(f.receipt));await assert.rejects(verifyConstantsArithmetic(f));});
await test('False JDK cached identity claim rejected',async()=>{const f=await fixture('identity');f.receipt.cachedJdkObjectIdentityClaimed=true;await writeFile(f.receiptPath,JSON.stringify(f.receipt));await assert.rejects(verifyConstantsArithmetic(f));});
await test('Changed dependency identity rejected',async()=>{const f=await fixture('dependency');f.receipt.sharedDependencies=[];await writeFile(f.receiptPath,JSON.stringify(f.receipt));await assert.rejects(verifyConstantsArithmetic(f));});
await test('Existing output rejected',async()=>{const f=await fixture('existing');await assert.rejects(prepareConstantsArithmetic(f));});
await test('Symlink output rejected',async()=>{const target=path.join(root,'target');await mkdir(target);const outputRoot=path.join(root,'link');await symlink(target,outputRoot);await assert.rejects(prepareConstantsArithmetic({sourceRoot,outputRoot}));});
await test('New identity-sensitive incoming caller rejected',async()=>{const file=path.join(root,'Incoming.kt');await writeFile(file,'val identity = checkBinaryOp(name,a,left,b,right) === left');await assert.rejects(auditIncomingIntegerCallers([{path:'Incoming.kt',filename:file}]));});
await test('New imported caller alias rejected',async()=>{const file=path.join(root,'Alias.kt');await writeFile(file,'import org.jetbrains.kotlin.resolve.constants.evaluate.checkBinaryOp as check');await assert.rejects(auditIncomingIntegerCallers([{path:'Alias.kt',filename:file}]));});
console.log(JSON.stringify({passed,failed:0,skipped:0,output:root}));
